### ISSUE TITLE
Incompability with current version of Terraria Overhaul

### ISSUE THREAD

**Issue by AtroCty** [Werebearguy/AssortedCrazyThings#10]
See title. Current version (compatible with 3.x) cannot work with the updated version of Terraria Overhaul. (4.x)

**Comment by direwolf420** [comment]
https://github.com/Werebearguy/AssortedCrazyThings/wiki/Troubleshooting:-Bugs-and-Known-Issues#compatibility

**Comment by direwolf420** [comment]
If you wish to play with the fixed version and new undocumented features, compile the 0_11 branch yourself

**Comment by direwolf420** [comment]
I compiled a version with specifically just that overhaul fix, check releases
