### ISSUE TITLE
Dessicated leather not dropping

### ISSUE THREAD

**Issue by nosoytunose** [Werebearguy/AssortedCrazyThings#19]
Or you changed it to not be a 100% drop and forgot to update the wiki,or it just drops very rarely.

**Comment by direwolf420** [comment]
On stable 1.4.3.6, it drops 2x100% in normal mode, and from the treasure bag it's 1x50%.
The latter behavior is a bug and it's fixed on the preview (1.4.4) version

**Comment by direwolf420** [comment]
Should be fixed as of today due to tml 1.4.4 releasing
