### ISSUE TITLE
"Reported from in-game: Test Issue (ignore)" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Werebearguy/AssortedCrazyThings#4]
| Mods:  | - | - |
| :--- | :--- | :--- |
| Assorted Crazy Things 1.2.2.1 | Boss Checklist 0.2 | Cheat Sheet 0.5.0.1 |
| Dark-Assassin's Mod Library (DALib) 1.2.3.1 | Example Mod 0.10.1.5 | Mod Helpers 4.2.2.1 |
| Helpful Hotkeys 1.5.5 | Idglib - Library for Coders 2.2 | ItemMagnetPlus 0.1.7 |
| Loot Bags 1.0.1 | Modders Toolkit 0.11 | Ophioid: A Boss fight mod 1.92 |
| pinkymod 1.1.0.1 | Player Resource Bars 1.1.1 | Shorter Respawn Time 0.2.5 |
| TerrariaHooks 0.13 | Variable Potion Sickness 1.0.1.1 | - |
 
Is day: True, Time of day/night: 11817, Elapsed half days: 1
 
World name: aaahardmode, world size: Small
 
World progress: King Slime killed, Wall of Flesh killed, Destroyer killed, Twins killed, Skeletron Prime killed, Golem killed
 
Items on ground: 23, Npcs active: 2
 
Player info: Name: `Testing`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 400 of 400 (200), Mana: 260 of 260, Defense: 48
 
Player equips: Head: Nebula Helmet, Body: Nebula Breastplate, Legs: Nebula Leggings, Accessory: Lightning Boots, Accessory: Sigil of Emergency, Accessory: Shield of Cthulhu, Accessory: Flame Wings, Vanity: Ancient Necro Helmet, Vanity: Sigil of Retreat, Vanity: Everburning Candelabra
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 1
 
Lighting threads: 3
 
Frame skip mode: 0
 
Is screen maximized: True
 
Screen resolution: 1283 669
 
Quality style: 1
 
Background on: True
 
Child safety: False
 
Game zoom: 1.430001
 
UI zoom: 1.496241
 
 
 
Recent error logs:
```
No error logs available.
```
 
Test Issue to see the format

**Comment by direwolf420** [comment]
Report made by me to test if it works correctly, ignore!
