### ISSUE TITLE
Megalodon thwarted by natural terrain

### ISSUE THREAD

**Issue by LenKagetsu** [Werebearguy/AssortedCrazyThings#8]
![image](https://user-images.githubusercontent.com/38071386/58059178-bdee4a80-7b63-11e9-99d5-02496d09afe0.png)

Where I'm standing, the Megalodon simply cannot touch me, this is done by getting under it and standing on the curve of the beach. I have Overhaul installed in case that somehow influenced the hitbox of myself or the megalodon (though very unlikely).

(The yellowing of the ocean is a bug in my world where the ocean extends beyond its usual limit, making the game think that portion is desert.)

**Comment by direwolf420** [comment]
We tweaked the hitbox of Megalodon a fair bit over the last few updates but there are always compromises. Such large hitboxes don't mesh well with terraria as a whole, if collisions are concidered (see: King Slime, he can teleport if he can't get to the player after a while).
We will leave it be for now, as Megalodon is a very rare spawn and in most cases it will pose such a threat to the player that he will try to avoid it after first engaging anyways
